# 安装glibc、bash、时区tzdata
# 默认为东八区
FROM latelee/alpine:glibc
 

RUN cd /tmp/ && \
	apk add --no-cache -U tzdata bash && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    rm -rf /var/cache/apk/* *.apk

#RUN cd /tmp/ && \
#    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
#    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
#    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_REPO}/glibc-${GLIBC_REPO}.apk && \
#    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_REPO}/glibc-bin-${GLIBC_REPO}.apk && \
#    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_REPO}/glibc-i18n-${GLIBC_REPO}.apk && \
#    apk add --force-overwrite --no-cache glibc-${GLIBC_REPO}.apk glibc-bin-${GLIBC_REPO}.apk glibc-i18n-${GLIBC_REPO}.apk && \
#    apk add --force-overwrite --no-cache --update libstdc++ && \
#	apk add -U tzdata bash && \
#    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
#    echo "Asia/Shanghai" > /etc/timezone && \
#    rm -rf /var/cache/apk/* *.apk

